### ISSUE TITLE
Button help when mouse passes over it.

### ISSUE THREAD

**Issue by mascapollo** [node-red/node-red-dashboard#244]
It is possible to have a pop up help window when the mouse passes over the button?

**Comment by knolleary** [comment]
Hi, no that is not a feature provided by the Button widget. You could create your own using the Template node and some custom html/javascript.
Hi, thanks for raising an issue.

By the way, we prefer to handle this sort of question on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!
