### ISSUE TITLE
bar chart not showing up

### ISSUE THREAD

**Issue by wumin1** [node-red/node-red-dashboard#261]
Hi,
I'm trying to plot a bar chart using node-red dashboard,however I can not find any document explains the input data format. I tried serval data structure(from nod-red google group) that claim to work. Some of them do not work at all, others can only drive line-chart but not bar-chart.

For instance: 
`[{ key: "storageKey", values: { data:[[1,2,3]], series:["a"], labels:["1", "2", "3"] }}];` 

`var chart =[
    {        "key": "Last 7 Days",
            "values": [
                             [1,25],
                             [2,30],
                             [3,16],
                             [4,20],
                             [5,23],
                             [6,40],
                             [7,10]
                          ]
    } ];`

What exactly is the input format for bar chart? Would someone kindly enlighten me please?

Ps, I would be also grateful if someone can tell me how to change x-axis label as index id? 

greetings

**Comment by dceejay** [comment]
hopefully now fixed by 5d20ac6f4fe37ea25201a41172f8cd01490e16a2

new format for bar chart (when using that fix) is

`[{"series":["A","B","C"],"data":[[9],[3],[7]],"labels":[" "]}]`

for bars of the same colour

`[{"series":[""],"data":[[5,6,9]],"labels":["A","B","C"]}]`

and these can be mixed - ie you can have series and labels defined...


for line charts it is

`[{"series":["A","B","C"],"data":[[{"x":1504029632890,"y":5},{"x":1504029636001,"y":4},{"x":1504029638656,"y":2}],[{"x":1504029633514,"y":6},{"x":1504029636622,"y":7},{"x":1504029639539,"y":6}],[{"x":1504029634400,"y":7},{"x":1504029637959,"y":9},{"x":1504029640317,"y":7}]],"labels":[""]}]`

**Comment by k5928** [comment]
Is there still a issue with this, because I can't get the bar chart working? Only thing that shows up is horizontal thin lines, but bars won't show up....

I tried both in above:

[{"id":"64737d74.3ba214","type":"ui_chart","z":"6328a76f.91f5f8","name":"daa","group":"60b9a354.b711cc","order":0,"width":"6","height":"5","label":"chart","chartType":"bar","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"ta","dot":false,"ymin":"0","ymax":"10","removeOlder":1,"removeOlderPoints":"","removeOlderUnit":"3600","cutout":0,"useOneColor":false,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"x":550,"y":140,"wires":[[],[]]},{"id":"f51eb6e2.bd6428","type":"function","z":"6328a76f.91f5f8","name":"","func":"msg.payload = [{\"series\":[\"\"],\"data\":[5,6,9],\"labels\":[\"A\",\"B\",\"C\"]}];\nreturn msg;","outputs":1,"noerr":0,"x":330,"y":140,"wires":[["64737d74.3ba214","a47fbd6c.2e431"]]},{"id":"34b8d1a9.184b7e","type":"inject","z":"6328a76f.91f5f8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":120,"y":140,"wires":[["f51eb6e2.bd6428"]]},{"id":"a47fbd6c.2e431","type":"debug","z":"6328a76f.91f5f8","name":"","active":true,"console":"false","complete":"true","x":540,"y":200,"wires":[]},{"id":"60b9a354.b711cc","type":"ui_group","z":"","name":"Sää","tab":"a3f9db6a.ed3b18","order":1,"disp":true,"width":"6"},{"id":"a3f9db6a.ed3b18","type":"ui_tab","z":"","name":"Sentiment","icon":"dashboard","order":3}]

**Comment by dceejay** [comment]
it works using the new format - using the new code on master (not npm)

msg.payload = [{"series":[""],"data":[[5,6,9]],"labels":["A","B","C"]}];

**Comment by k5928** [comment]
Sorry for being newbie, but what does that mean? I am using node red in IBM Bluemix and I have added the node to the palette.

**Comment by dceejay** [comment]
it means the version in Bluemix doesn't have the fix yet - so bar charts won't show up correctly.

**Comment by k5928** [comment]
ok, thanks.
