### ISSUE TITLE
UI Menu-Button could integrate UI better in Node-RED

### ISSUE THREAD

**Issue by biancode** [node-red/node-red-dashboard#286]
Dear Dave,

it would be great to get a button for the UI link in the right upper corner as the User-Button.
Many people did not find, how to call the UI if they are new in Node-RED.

![image](https://user-images.githubusercontent.com/4369867/30794220-434fffac-a1c7-11e7-9e6f-bf3929a46a90.png)

Thanks a lot!
Klaus

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle feature requests or suggestions on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

In this instance, Node-RED doesn't provide any mechanism for a node to add a button to the title bar so there's nothing it can do here.

Thanks!

**Comment by dbaba** [comment]
@biancode You can find a link to the UI from the dashboard tab, which, I think, the shortest way for newbies to get there.
<img width="316" alt="this" src="https://user-images.githubusercontent.com/1858156/30866068-36e8501e-a313-11e7-8a83-2554ef5b91b0.png">

**Comment by biancode** [comment]
Thanks!

**Comment by dceejay** [comment]
and by default it creates a keyboard shortcut -  ctrl (or cmd) - shift - d
