### ISSUE TITLE
Chart not displaying on Ubuntu/Firefox

### ISSUE THREAD

**Issue by bry1226** [node-red/node-red-dashboard#291]
I am receiving MQTT messages and putting them into a Map object. I then take the Map, convert it into a JSON, sort it and output the top 5 results using eval in a function block. The chart is not displaying any data from the function node that is running the code that is building the Map. I am running on Ubuntu 16.04.3 LTS with Firefox version 56. It also appears that the function block is not running even if I perform a direct injection of an empty string or timestamp. Another chart I have that has an input of a regular array displays information correctly.

Can anyone help with the chart display issue?

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!

**Comment by bry1226** [comment]
Ok sorry about that, thanks for the guidance
