### ISSUE TITLE
Showing Image Using Template Node

### ISSUE THREAD

**Issue by robertatdi** [node-red/node-red-dashboard#297]
I have set up my node-red using setup.js to pull files from a local folder on the raspberry pi. From there I use a template node to display the image on the UI using: 

<img style="width: 100%" ng-src='/myimage.png'>

This works to display the image about 50% of the time. The other 50% of the time the image does not show up unless I refresh the UI a few times. Does anyone have the same problem or a resolution so that it always shows up?

**Comment by dceejay** [comment]
Hi, thanks for raising an issue.

If you check out our contribution guidelines you'll see we prefer to handle this sort of thing on the mailing list, slack team or you could ask a question on Stack Overflow and tag it node-red. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!
