### ISSUE TITLE
The ui interface appears empty

### ISSUE THREAD

**Issue by RohanAsmat** [node-red/node-red-dashboard#317]
After installing node-red-dashboard when I hit the ui interface using following:
 http://localhost:1880/ui

I see empty screen with an empty navigation bar and grey area in rest of the screen!

Any clue what is going wrong here?

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle general support requests on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!

**Comment by knolleary** [comment]
One quick suggestion - have you added an ui widgets to your flow? If you haven't, then your dashboard will be empty.

**Comment by RohanAsmat** [comment]
I will raise a new issue as a suggestion for UX improvement.

**Comment by knolleary** [comment]
@RohanAsmat ok, but for future reference, as per my original comment, please raise things on the mailing list first before opening an issue.

**Comment by dceejay** [comment]
Happy to look ar any code/designs you may have to fill the space
