### ISSUE TITLE
Charts Y-scale

### ISSUE THREAD

**Issue by selfus** [node-red/node-red-dashboard#328]
Currently is is possible to define Ymin and Ymax, but no scale. 

Would it be possible to add a Yscale, instaed of it being automatic?

**Comment by dceejay** [comment]
Hi, as per our contribution guidelines we prefer general comments and discussion of new features on the mailing list or slack channel so that the widest possible community can join in, leaving the issues list for actual code issues.

Currently there is no plan to add any extra scaling function as we are trying to keep it as simple as possible for users - they can either let it be totally automatic, specify just min or min and max, and the scale will respond appropriately within the constraints of the space available. But happy to discuss in the wider fora.
