### ISSUE TITLE
change min / max value on gauges dynamically

### ISSUE THREAD

**Issue by tbowmo** [node-red/node-red-dashboard#336]
Is it possible to change the min / max values on gauges dynamically?

I'm integrating a iGrill2 grilling thermometer into my home automation setup, and want to have it on a dashboard, so that I can use a numeric input to set a target temperature for the meat, and would like the max value of the gauges to represent the chosen target temperature (+5 degrees)

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.


To answer your question, yes it is possible. https://github.com/node-red/node-red-dashboard/blob/master/config-fields.md


Thanks!
