### ISSUE TITLE
Issue with charts

### ISSUE THREAD

**Issue by Shirola** [node-red/node-red-dashboard#354]
Every time I change my value globally, the chart creates a new bar and legend instead of refreshing over existing data. In this case I only have 3 data.
![image](https://user-images.githubusercontent.com/35582142/36287033-50445c00-1317-11e8-831b-c0426e01b19a.png)

**Comment by dceejay** [comment]
Hi - in general we prefer how-to type questions via the mailing list or slack channel so that the widest possible audience can help out. You don't say what version of dashboard you are using or how you are sending the data. You can only send one piece of data at a time. As long as the topic for each remains the same they will overwrite.

**Comment by dceejay** [comment]
Closing - no repsonse
