### ISSUE TITLE
node-red-dashboard template html

### ISSUE THREAD

**Issue by sultan87** [node-red/node-red-dashboard#357]
hello,
here is my template

[template.txt](https://github.com/node-red/node-red-dashboard/files/1748687/template.txt)

I would like to display in red if negative if not in blue
how to do?
best regards

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!
