### ISSUE TITLE
Dashboard elements ID

### ISSUE THREAD

**Issue by Silvia-t** [node-red/node-red-dashboard#358]
Hi all,

It would be nice if the dashboard elements (inputs, graphs, etc.) could be given a fixed ID so that they can be styled or whatever using a template node.

Thanks :)

**Comment by dceejay** [comment]
Hi - as per our contribution guidelines we prefer suggestions and request to be made via the google group mailing list or the slack channel so they can be discussed by the wider community. Rather than being raised as an issue against code that is working.

Some thoughts - how would they be fixed ? (what would guarantee uniqueness ? Which container level would be tagged ? the div ? the md-card ? 

Many thanks
