### ISSUE TITLE
No Map dashBoard ui

### ISSUE THREAD

**Issue by muzmmilkhan** [node-red/node-red-dashboard#361]
sir pleas make a map dashboard or simply give me some adderes where i can use map as dashboard 
sir i have mqtt broker and lat,long co-ordinats and i want plot it on ui .i try worldmap but it is complicated .

**Comment by knolleary** [comment]
Hi - node-red-contrib-web-worldmap is what you're asking for. We're not going to create another map widget when we already have that one.

If you are having trouble using it, then please do ask on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!

**Comment by dceejay** [comment]
If you have it installed there are some examples installed with it - under the menu (top right) - Import - Examples - Worldmap

**Comment by muzmmilkhan** [comment]
Sir Thanks i try the example and it works than you but it give the error that is "type: "keynotfound"
description: "this key does not exist"" what shoud i do

**Comment by dceejay** [comment]
which example ?
Is this as imported or have you modified it ?

**Comment by muzmmilkhan** [comment]
I have importe this from- under the menu (top right) - Import - Examples - Worldmap
