### ISSUE TITLE
Charts with Live and Stored data

### ISSUE THREAD

**Issue by Quentintin** [node-red/node-red-dashboard#362]
Hello,

Each 30 minutes, I get a message from MQTT with data to store in Charts. Easy, you'll say ! 
But the main problem is my message logs value with differents timestamps

e.g : 
- message **ABCDEFGH** (in Hexadecimal)
   - **AB** is value for Time 0 (When i received the message)
   - **CD** is value for T0-10min
   - **EF** is value for T0-20min
   - **GH** is value for T0-30min

So I need a method to push data lively into Charts but with delay.
Any solution ?

Thank you !

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!

**Comment by Quentintin** [comment]
Ok, i push on Slack
