### ISSUE TITLE
ui blank page 

### ISSUE THREAD

**Issue by yassersaber** [node-red/node-red-dashboard#369]
it was working !
but in the last try to access nodered IP address /ui appear blank page like attached 
i tryed 
1-reboot
2-uninstall and install dashboard and ui 
3- remove all flow 
4-use another browser 
but still not solve the problem
![problem dashbord](https://user-images.githubusercontent.com/28996178/37637168-40202228-2c17-11e8-8fda-bdadd098939c.jpg)

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

As you've already emailed the mailing list and asked this on slack, I'm going to close this issue so it can be dealt with on one of those other places.

Thanks!
