### ISSUE TITLE
Inject js in page

### ISSUE THREAD

**Issue by SergiuToporjinschi** [node-red/node-red-dashboard#370]
Hi, I don't know if this was already proposed but I think is quite util to have a section somewhere in dashboard tab in administration; Where to add some js links to be included before loading the dashboard;
Yes I can to js inject in header by using a template but this is loaded with a delay and in the next template where I want to use it I have to put a timeout and check if the component from my js is loaded;

For example I wanted to have highCharts included in the page so I had to create a template with the CDN inject link in a template set to inject content in header; 
And in the template node that is putting the chart in page I have something like
`  var timmer = setInterval(function(){
        if (!window.Highcharts) return;
        clearInterval(timmer);
})`

**Comment by dceejay** [comment]
As per the contribution guidelines we prefer suggestions and discussions on the mailing list or via the slack channels first so the issues can be kept for bugs and fixes.
As you point out the default mechanism we have is to use the ui_template to add extra libraries via the header. Once loaded it should remain available to all pages. You can of course point to local files rather than a CDN if that would speed things up.
If you want full control of your web page then you may want to consider the node-red-contrib-uibuilder project that allows you to develop the dashboard as you wish.

**Comment by SergiuToporjinschi** [comment]
aaa sorry I'm closing this ticket
