### ISSUE TITLE
how to keep the data after reboot ?

### ISSUE THREAD

**Issue by msongz** [node-red/node-red-dashboard#374]
hi, I install node-red on pi2 and getting data from some websites.
and dashboard works fine! I can see the data chart on life.
but after I reboot the device, all data will be lost.
I have no idea how to fix this problem, please help

**Comment by dceejay** [comment]
Hi

as per our contribution guidelines we prefer general ho-to type questions via the mailing list or slack channel so that widest possible community can step in and help. Leaving the Issues list for actual bugs and so on.

Correct - we do not persist data over a reboot - that is down to you and how you want to do that. The output on the chart node does provide an output with all the current dat in so you can persist it somewhere if you like.

for example  - https://flows.nodered.org/flow/92920b4fd450bf92a3035e061947daa0

**Comment by Soundfaction** [comment]
This is easier to use and requires no copying of nodes around or configuration of filenames:
https://www.hexamail.com/guides/node-red/persistcharts.htm
