### ISSUE TITLE
Connection lost on Internet lost

### ISSUE THREAD

**Issue by Proone01** [node-red/node-red-dashboard#390]
Hi, 

I use a Siemens Simatic IoT2040 with Node-Red embeded.

Eth0 : Internet (DHCP)
Eth1 : my computer (192.168.200.10)

I use local connexion to access Node-Red dashboard and Eth0 to transmit data to CLOUD.

When i unplug Eth0 (to simulate a network malfunction), data are transmited in Sigfox with an UART interface. But when i unplug Eth0, switching is OK, but dashboard crash ("Connection lost").

I can't access the Node-Red interface while Eth0 is unplugged.

Nothing happend when dashboard crash in logs.
But when i plug it back, there is something.

Do you know what happend ?

Best regards !

[LOGS.txt](https://github.com/node-red/node-red-dashboard/files/1984552/LOGS.txt)

**Comment by dceejay** [comment]
Hi - as per the contribution guidelines in general we prefer questions via the slack channel or mailing list in the first instance so the widest possible community can see and possibly help, rather than rely on the core developers. As it happens I have not got any experience of that device so I can't really comment other than to suggest you check in other ways (such as ping) that the eth1 port is still reachable from your laptop.
