### ISSUE TITLE
NodeRed Dashboard auto start when Raspberry pi reboot

### ISSUE THREAD

**Issue by S-Idris** [node-red/node-red-dashboard#399]
Hi All,

I know how to run NodeRed on startup by using following command.
`sudo systemctl enable nodered.service`

but I am using dashboard in my NodeRed flows and want to see the **dashboard window to appear as I reboot the Raspberry pi**.
How can I do this?

Syed Idris

**Comment by dceejay** [comment]
Hi - When you created this issue did you not see the template ? that says

## Before you hit that Submit button....

This issue tracker is for problems with the Node-RED-Dashboard only.

If your issue is:
  - a general 'how-to' type question,
  - a feature request or suggestion for a change

please use the Dashboard category in the [Node-RED Forum](https://discourse.nodered.org) or [slack team](https://nodered.org/slack).

This is a general Linux question re launching an application on start.
