### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by luamiennam** [node-red/node-red-dashboard#410]
### Please tell us about your environment:

- [ ] Node-RED-Dashboard version:
- [ ] Node-RED version: 0.18.7
- [ ] node.js version: 8.9.4
- [ ] npm version: 
- [ ] Platform/OS: NAS Ds3615xs
- [ ] Browser:

I installed the following syntax: https://hub.docker.com/r/nodered/node-red-docker/
(link: https://hub.docker.com/r/nodered/node-red-docker/)
But when the dashboard setup for the red node is the error as shown. Has anyone ever encountered an error request processing instructions. Thanks
https://sv1.uphinhnhanh.com/images/2018/07/07/425c48.jpg

p/s: sorry my enghlish not good.

**Comment by dceejay** [comment]
Hi 

A quick google would suggest it may be an issue with the version of npm you have  ` npm -v `
then ` sudo npm -i  np@latest ` to update. Then retry the install.

I don't think many of the core developers use docker regularly enough and certainly not on a NAS to be much help, so asking more widely would be a good idea. as the issue form you filled in said 
"please use the Dashboard category in the [Node-RED Forum](https://discourse.nodered.org) or [slack team](https://nodered.org/slack).

You could also consider asking a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.

That way the whole Node-RED user community can help, rather than rely on the core development team."

**Comment by dceejay** [comment]
closing due to lack of response
