### ISSUE TITLE
Localtime v.s. server time

### ISSUE THREAD

**Issue by Travelbacon** [node-red/node-red-dashboard#425]
During a stay in another time zones, I've found out that the elements take over the local time from the browser instead of the local time of the server. This can cause very strange behavior of the modules.

I think it would be very welcome for an option in the nodes which time to display. Mine example  is that my light sensor tells me it is 11 o'clock in the evening. But the indicator in the webpage tells me it is was local time (5 PM).  When you travel a lot between zones, like I did from MT and PT, while the server is in CET, you will get unwanted behavior in the #ui in the webpage. Ugly graphs or display nothing at all.

Can there be an option to select which time to select in the Dashbord? Server, local, or specific?

**Comment by dceejay** [comment]
As per the issue template you deleted 
"If your issue is:
  - a general 'how-to' type question,
  - a feature request or suggestion for a change

please use the Dashboard category in the [Node-RED Forum](https://discourse.nodered.org) or [slack team](https://nodered.org/slack)."

This may indeed be a valid request but currently I have no bandwidth to even contemplate it - so would need to rely on help and ideally a Pull Request from the wider community.

**Comment by Travelbacon** [comment]
My apologies. I should have given more proof why it is not working and why I reported as an issue and post it to the forum. I over read the part of the forum.

**Comment by patricktokeeffe** [comment]
https://discourse.nodered.org/t/dashboard-line-chart-stored-data-and-timestamps/3411
