### ISSUE TITLE
Mobile styling - 100% width

### ISSUE THREAD

**Issue by bakman2** [node-red/node-red-dashboard#432]
### What are the steps to reproduce?
Create a standard dashboard with a button or widget

### What happens?
The layout is not 100% width on mobile (or at least on an iPhone) and has precious empty space left/right.

### What do you expect to happen?
Paddings/margins removed on mobile and have a full width layout.

### Please tell us about your environment:

- [x] Node-RED-Dashboard version:2.9.8
- [x] Node-RED version: v0.19.3
- [x] node.js version: v8.11.4
- [x] npm version:5.6.0
- [x] Platform/OS: Linux 4.14.62-v7+ arm LE
- [x] Browser: Safari mobile

Is there a way to reduce the font-size for the chart titles ? 
I would like to remove all the large paddings/heights, is this possible somehow ? 

Playing around with the widget sizes/group sizes messes up the layout (try setting the group spacing to 0 and you end up with 1 column)

**Comment by dceejay** [comment]
In general we prefer how-to type questions via the main discourse forum (dashboard section) - or via the slack channel - that way more members of the community can offer help. 

The dashboard is based on fixed width groups that then reflow across the space available. There is no concept of 100% width - so you will need to adjust the basic width units so that one group fits the width of your screen appropriately - using the site sub-tab within the dashboard tab on the right of the workspace.

You can override the css of most items by using a ui-template node containing suitable markup.
