### ISSUE TITLE
Theme can not be exported

### ISSUE THREAD

**Issue by LeonardAB** [node-red/node-red-dashboard#457]
### What are the steps to reproduce?
1. Create a flow with some dashboard nodes, and create a custom theme (other than dark/light)
2. export the flow, either through clipboard or library
3. open a new instance of node-red in another PC
4. import the flow

### What happens?
The nodes were imported but the customized theme were not. The UI used either the dark or light theme.

### What do you expect to happen?
The theme should also be imported / exported, so the UI would like exactly like the initially created one.

### Please tell us about your environment:

- [x] Node-RED-Dashboard version: 2.12.2
- [x] Node-RED version: 0.19.5
- [x] node.js version: 8.11.4
- [x] npm version: 5.6.0
- [x] Platform/OS: Win 10 Pro
- [x] Browser: Chrome 71.0.3578.80 

Thanks!

**Comment by dceejay** [comment]
In general we prefer questions via the discourse forum or slack channel first so that the widest possible audience can see and help respond.

The theme is held in the base node which being a config node is not held in the visible flow - so to export it you must select the All flows option - then when you import you will get the base configuration node back with the current theme in.
![image](https://user-images.githubusercontent.com/5375409/49869254-d1082c00-fe07-11e8-94f3-2688aba8a8bc.png)
