### ISSUE TITLE
User Login System With Token,Sessions And Forgot Password Recovery

### ISSUE THREAD

**Issue by mralperem** [node-red/node-red-dashboard#471]
Hello,

I am currently developing a raspberry pi based home automation system. I am going to use Raspberry Pi as the hub of my system and Esp8266 chips to automate stuffs. 

I would like to implement user login/autentication system with sessions and forgot password recovery link.
I have tried a lot of thing but unfortunetly lack of documents on the internet and my knowledge I wasnt able to do that. So I wanted to ask that if it is possible with this dashboard and node-red or I am just trying for something which is not gonna work.

I also would like to ask you that how can I change the style of the dashboard. For example I want to keep the hamburger menu but I just wanted it to be seen on mobile not on desktop or I wanted to add a bottom navigation bar on the desktop site and hide that on mobile and so on.

Thank you in advance

**Comment by dceejay** [comment]
We prefer general discussion and feature requests to be either on the slack channel or via the discourse forum where many more of the community can contribute and help out, leaving the issue list for actual code issues.

This dashboard is a single user system - due to the way it is tied closely to the core of Node-RED. All the changes you mention are of course possible but would need a serious digging into the code to accomplish which you would have to do yourself. 

A better alternative may be to look at the `node-red-contrib-uibuilder` project as that allows much greater freedom and you can use whatever framework library you like to build the front end in whatever style you wish, and thus design in multi-user capability as you wish. Good luck with your development.
