### ISSUE TITLE
please add support for float values for the slider

### ISSUE THREAD

**Issue by salilahuja** [node-red/node-red-dashboard#68]
Please add support for float values for the slider. After a lot of hit and try,we figured the issue was we were sending a float value. ( thanks @dancunnington )

**Comment by natcl** [comment]
Note that you can use the range object to convert in ranges to floats.

**Comment by dceejay** [comment]
or  use a function to divide the slider output by 10 100 etc ...

**Comment by salilahuja** [comment]
@natcl float values did not work for me with slider. I had to change it to int type. Is that by design for slider ?

**Comment by dceejay** [comment]
sorry - what is the actual issue here ? what do you need to change to int ?

Yes the slider currently only outputs integer values - but should accept floats and slide to the appropriate position.

Yes we can look at adding a step value so you can send out floats... but is there an other problem also ?
