### ISSUE TITLE
Dropdown outputs number instead of string 

### ISSUE THREAD

**Issue by ihbar** [node-red/node-red-dashboard#691]
### What are the steps to reproduce?

Create a dropdown node including a choice with string value 2
See details in https://discourse.nodered.org/t/what-should-be-the-type-of-dropdown-output/42673

### What happens?
when it is selected, the node sends 2 as number, not as a string

### What do you expect to happen?
I expect to received a string

Problem is not visible on dashboard 2.27.0

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.28.1 or 2.28.0,
- [ ] Node-RED version: 1.2.9
- [ ] node.js version: 12.19.1
- [ ] npm version: 6.14.8
- [ ] Platform/OS: windows
- [ ] Browser: chrome

**Comment by colinl** [comment]
I have been testing this and can confirm that if the dropdown is configured to send any string value that is a valid number then it sends a numeric value rather than the string (at least for the numbers I have tried).
I have also confirmed the regression was introduced with 2.28.0.  In the thread linked I wrongly said that it also happened in 2.28.2, I was actually using the dashboard from git master so this was an early version of 2.28.2.  That version has not yet been released.

@ihbar could you edit the description so that it states that it fails on 2.28.0 and 2.28.1, but not on 2.27.0?

Here is a simple flow showing the problem.
```
[{"id":"81a5b5ba.fbd488","type":"ui_dropdown","z":"84405ff5.25fa6","name":"","label":"","tooltip":"","place":"Select option","group":"61285987.c20328","order":2,"width":0,"height":0,"passthru":true,"multiple":false,"options":[{"label":"21.0 should be string","value":"21.0","type":"str"},{"label":"21.5 should be string","value":"21.5","type":"str"},{"label":"21.5x string","value":"21.5x","type":"str"},{"label":"22 should be number","value":22,"type":"num"}],"payload":"","topic":"topic","topicType":"msg","x":180,"y":900,"wires":[["1592859e.122ca2"]]},{"id":"1592859e.122ca2","type":"debug","z":"84405ff5.25fa6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":350,"y":900,"wires":[]},{"id":"61285987.c20328","type":"ui_group","name":"Main","tab":"e7c46d5e.a1283","order":1,"disp":true,"width":"6","collapse":false},{"id":"e7c46d5e.a1283","type":"ui_tab","name":"Dashboard","icon":"dashboard"}]
```

**Comment by ihbar** [comment]
Hello 
I have tested the version 2.28.2, it is working perfectly. 
thanks a lot
