### ISSUE TITLE
Border - a feature request or suggestion for a change

### ISSUE THREAD

**Issue by sblogoshs** [node-red/node-red-dashboard#704]
Hello.

I would like to be able to change the border around a _button depending on payload_. Just like msg.color or msg.background a **msg.border** should be possible to change the border color/width.

Greetings Stefan

NodeRed 1.3.5
NPM 7.14.0
node.js 10.24.0
Dashboard 2.29.1
iPadOS 14.6
Safari iPad

**Comment by dceejay** [comment]
Hi,
as per the Issue template you have managed to delete
"
If your issue is:
  - a general 'how-to' type question,
  - a feature request or suggestion for a change

please use the Dashboard category in the [Node-RED Forum](https://discourse.nodered.org) or [slack team](https://nodered.org/slack).
"
We use the angular material library for a default set of styles and that does not include any border as they have chosen flat styling. You are able to implement your own buttons using the ui-template widget as many have done (see discourse forum) and that could be styled any way you choose.
