### ISSUE TITLE
Problem with losing Tabs and Groups

### ISSUE THREAD

**Issue by protolyser** [node-red/node-red-dashboard#74]
I'm setting up a node-red home control for the first time.
I have to flows currently:
- flow1 with buttons for LED controllers
- flow 2 with switches for power sockets

First all worked, then it got messed up.
I had only 1 tab: Home and 2 groups, suddenly switches lost their groups.
Then I deleted all groups and tabs and started over. 
I choose Add new ui_group on a switch on flow1 and generated the tab home again.
Then on flow2 the group isn't visible and I have to "Add new ui_group" again. And generate the tab home again. After that I have to "homes" not 1 like I want. Pushing it on the right dashboard with the mouse in the correct group worked first, but later I couldn't even delete empty groups.

Seems like there are some bugs with groups and the mouse drag & drop features.

Can't I use different Flows (for better overview) that use the same UI dashboard groups and tabs?

**Comment by dceejay** [comment]
Is this using the 2.0.2 version from npm ? or the latest from master on github ?

**Comment by knolleary** [comment]
@protolyser Config nodes, such as ui_group and ui_tab, can be scoped so they are only available to a particular flow. By default, they get scoped to the flow you are on when you create them. In the node's edit dialog, you can change the scope via the drop-down in the bottom right corner - if you change that to 'global', it is then available on all tabs.

The behaviour you are seeing is all due to this scoping. If you change your original ui_group/_tab nodes to be scoped globally, you can use them on all your flows and that will stop the behaviour you are seeing.

This type of issue is due to the non-intuitive behaviour around scoping of config nodes. As such, in the imminent 0.15.0 release of Node-RED, we default config nodes to be global, not flow-scoped.
