### ISSUE TITLE
Style attribute lost in text and template nodes

### ISSUE THREAD

**Issue by hobbyquaker** [node-red/node-red-dashboard#87]
I'm trying to visualize the color of a hue lamp, so I generate a msg in a function node with 
```
return {payload: '<div style="background-color:#' + msg.payload + '; width: 16px; height: 16px; border-radius: 8px;"></div>'}; 
``` 
and tried to feed that into a template or text node. Sadly the style attribute doesn't survive this. Is this a bug or expected behavior? If it's not a bug - do you have a hint on how one could visualize a color?

**Comment by dceejay** [comment]
Hi,
for general questions please use the google group or slack first.
This is not a bug. It's a feature of Angular security stripping out extra styling due to security concerns. You can either use the pre-defined classes - 
.nr-dashboard-error
.nr-dashboard-warning
.nr-dashboard-ok
.nr-dashboard-dim 

or send in the colour in html - eg [{"id":"11795acc.11dc85","type":"ui_text","z":"3ee56046.c933c","group":"ca294884.9f6a68","order":5,"width":"1","height":"1","name":"on/off","label":"","format":"<font color={{(msg.payload?\"red\":\"grey\")}}><i class=\"fa fa-lightbulb-o fa-2x\"></i></font>","layout":"row-center","x":810,"y":580,"wires":[]},{"id":"8f17522e.afaac","type":"ui_switch","z":"3ee56046.c933c","name":"","label":"switch","group":"ca294884.9f6a68","order":0,"width":0,"height":0,"passthru":true,"topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":640,"y":580,"wires":[["11795acc.11dc85"]]},{"id":"ca294884.9f6a68","type":"ui_group","z":"3ee56046.c933c","name":"Click","tab":"513b7ff4.3de5d","order":2,"disp":true,"width":"4"},{"id":"513b7ff4.3de5d","type":"ui_tab","z":"3ee56046.c933c","name":"Home","icon":"link","order":1}]
